// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/AndTemplate.jamon

package VMTranslator.templates;


public class AndTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.AndTemplate.Intf

{
  protected static VMTranslator.templates.AndTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.AndTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public AndTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.AndTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 1, 1
    jamonWriter.write("// x & y\r\n@SP\r\nM=M-1\r\nA=M\r\nD=M\r\n@SP\r\nA=M-1\r\nM=D&M");
  }
  
  
}
