// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/FunctionTemplate.jamon

package VMTranslator.templates;


public class FunctionTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.FunctionTemplate.Intf

{
  private final String f;
  private final int k;
  protected static VMTranslator.templates.FunctionTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.FunctionTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public FunctionTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.FunctionTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    f = p_implData.getF();
    k = p_implData.getK();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 6, 1
    jamonWriter.write("// function ");
    // 6, 13
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f), jamonWriter);
    // 6, 20
    jamonWriter.write(" ");
    // 6, 21
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(k), jamonWriter);
    // 6, 28
    jamonWriter.write("\r\n(");
    // 7, 2
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(f), jamonWriter);
    // 7, 9
    jamonWriter.write(")\r\n");
    // 8, 1
    for (int i=0; i < k; i++ )
    {
      // 8, 29
      jamonWriter.write("\r\n@SP\r\nM=M+1\r\nA=M-1\r\nM=0\r\n");
    }
    // 13, 8
    jamonWriter.write("\r\n");
  }
  
  
}
