// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/IfTemplate.jamon

package VMTranslator.templates;


public class IfTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.IfTemplate.Intf

{
  private final String b;
  protected static VMTranslator.templates.IfTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.IfTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public IfTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.IfTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    b = p_implData.getB();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 5, 1
    jamonWriter.write("// if-goto ");
    // 5, 12
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(b), jamonWriter);
    // 5, 19
    jamonWriter.write("\r\n@SP\r\nM=M-1\r\nA=M\r\nD=M\r\n@");
    // 10, 2
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(b), jamonWriter);
    // 10, 9
    jamonWriter.write("\r\nD;JNE\r\n");
  }
  
  
}
