// Autogenerated Jamon proxy
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/IfTemplate.jamon

package VMTranslator.templates;


@org.jamon.annotations.Template(
  signature = "3E774837A9E2AB81DE96DE99FEF35F12",
  requiredArguments = {
    @org.jamon.annotations.Argument(name = "b", type = "String")})
public class IfTemplate
  extends org.jamon.AbstractTemplateProxy
{
  
  public IfTemplate(org.jamon.TemplateManager p_manager)
  {
     super(p_manager);
  }
  
  public IfTemplate()
  {
     super("/VMTranslator/templates/IfTemplate");
  }
  
  protected interface Intf
    extends org.jamon.AbstractTemplateProxy.Intf{
    
    void renderNoFlush(final java.io.Writer jamonWriter) throws java.io.IOException;
    
  }
  public static class ImplData
    extends org.jamon.AbstractTemplateProxy.ImplData
  {
    // 2, 3
    public void setB(String b)
    {
      // 2, 3
      m_b = b;
    }
    public String getB()
    {
      return m_b;
    }
    private String m_b;
  }
  @Override
  protected ImplData makeImplData()
  {
    return new ImplData();
  }
  @Override @SuppressWarnings("unchecked") public ImplData getImplData()
  {
    return (ImplData) super.getImplData();
  }
  
  
  @Override
  public org.jamon.AbstractTemplateImpl constructImpl(Class<? extends org.jamon.AbstractTemplateImpl> p_class){
    try
    {
      return p_class
        .getConstructor(new Class [] { org.jamon.TemplateManager.class, ImplData.class })
        .newInstance(new Object [] { getTemplateManager(), getImplData()});
    }
    catch (RuntimeException e)
    {
      throw e;
    }
    catch (Exception e)
    {
      throw new RuntimeException(e);
    }
  }
  
  @Override
  protected org.jamon.AbstractTemplateImpl constructImpl(){
    return new IfTemplateImpl(getTemplateManager(), getImplData());
  }
  public org.jamon.Renderer makeRenderer(final String b)
  {
    return new org.jamon.AbstractRenderer() {
      @Override
      public void renderTo(final java.io.Writer jamonWriter)
        throws java.io.IOException
      {
        render(jamonWriter, b);
      }
    };
  }
  
  public void render(final java.io.Writer jamonWriter, final String b)
    throws java.io.IOException
  {
    renderNoFlush(jamonWriter, b);
    jamonWriter.flush();
  }
  public void renderNoFlush(final java.io.Writer jamonWriter, final String b)
    throws java.io.IOException
  {
    ImplData implData = getImplData();
    implData.setB(b);
    Intf instance = (Intf) getTemplateManager().constructImpl(this);
    instance.renderNoFlush(jamonWriter);
    reset();
  }
  
  
}
