// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/NegTemplate.jamon

package VMTranslator.templates;


public class NegTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.NegTemplate.Intf

{
  protected static VMTranslator.templates.NegTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.NegTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public NegTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.NegTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 1, 1
    jamonWriter.write("// -y\r\n@SP\r\nA=M-1\r\nM=-M\r\n");
  }
  
  
}
