// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/PushStaticTemplate.jamon

package VMTranslator.templates;


public class PushStaticTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.PushStaticTemplate.Intf

{
  private final String filename;
  private final Integer index;
  protected static VMTranslator.templates.PushStaticTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.PushStaticTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public PushStaticTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.PushStaticTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    filename = p_implData.getFilename();
    index = p_implData.getIndex();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 6, 1
    jamonWriter.write("// push static ");
    // 6, 16
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(index), jamonWriter);
    // 6, 27
    jamonWriter.write("\r\n@");
    // 7, 2
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(filename), jamonWriter);
    // 7, 16
    jamonWriter.write(".");
    // 7, 17
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(index), jamonWriter);
    // 7, 28
    jamonWriter.write("\r\nD=M\r\n@SP\r\nM=M+1\r\nA=M-1\r\nM=D\r\n");
  }
  
  
}
