// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project08/./VMTranslator/templates/SubTemplate.jamon

package VMTranslator.templates;


public class SubTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.SubTemplate.Intf

{
  protected static VMTranslator.templates.SubTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.SubTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public SubTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.SubTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 1, 1
    jamonWriter.write("// x - y\r\n@SP\r\nM=M-1\r\nA=M\r\nD=M\r\n@SP\r\nA=M-1\r\nM=M-D\r\n");
  }
  
  
}
