// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/eq.jamon

package VMTranslator.templates;


public class eqImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.eq.Intf

{
  protected static VMTranslator.templates.eq.ImplData __jamon_setOptionalArguments(VMTranslator.templates.eq.ImplData p_implData)
  {
    return p_implData;
  }
  public eqImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.eq.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
  {
  }
  
  
}
