// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/pop_const.jamon

package VMTranslator.templates;


public class pop_constImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.pop_const.Intf

{
  protected static VMTranslator.templates.pop_const.ImplData __jamon_setOptionalArguments(VMTranslator.templates.pop_const.ImplData p_implData)
  {
    return p_implData;
  }
  public pop_constImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.pop_const.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
  {
  }
  
  
}
