// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/PopStaticTemplate.jamon

package VMTranslator.templates;


public class PopStaticTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.PopStaticTemplate.Intf

{
  private final String filename;
  private final Integer index;
  protected static VMTranslator.templates.PopStaticTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.PopStaticTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public PopStaticTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.PopStaticTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    filename = p_implData.getFilename();
    index = p_implData.getIndex();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 6, 1
    jamonWriter.write("// pop static ");
    // 6, 15
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(index), jamonWriter);
    // 6, 26
    jamonWriter.write("\r\n@SP\r\nM=M-1\r\nA=M\r\nD=M\r\n@");
    // 11, 2
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(filename), jamonWriter);
    // 11, 16
    jamonWriter.write(".");
    // 11, 17
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(index), jamonWriter);
    // 11, 28
    jamonWriter.write("\r\nM=D\r\n");
  }
  
  
}
