// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/push.jamon

package VMTranslator.templates;


public class pushImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.push.Intf

{
  protected static VMTranslator.templates.push.ImplData __jamon_setOptionalArguments(VMTranslator.templates.push.ImplData p_implData)
  {
    return p_implData;
  }
  public pushImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.push.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
  {
  }
  
  
}
