// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/PushConstantTemplate.jamon

package VMTranslator.templates;


public class PushConstantTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.PushConstantTemplate.Intf

{
  private final Integer num;
  protected static VMTranslator.templates.PushConstantTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.PushConstantTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public PushConstantTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.PushConstantTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
    num = p_implData.getNum();
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 5, 1
    jamonWriter.write("// push constant ");
    // 5, 18
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(num), jamonWriter);
    // 5, 27
    jamonWriter.write("\r\n@");
    // 6, 2
    org.jamon.escaping.Escaping.HTML.write(org.jamon.emit.StandardEmitter.valueOf(num), jamonWriter);
    // 6, 11
    jamonWriter.write("\r\nD=A\r\n@SP\r\nM=M+1\r\nA=M-1\r\nM=D\r\n");
  }
  
  
}
