// Autogenerated Jamon implementation
// C:/cygwin/home/Thea/cs498/src/project07/./VMTranslator/templates/PushTemplate.jamon

package VMTranslator.templates;


public class PushTemplateImpl
  extends org.jamon.AbstractTemplateImpl
  implements VMTranslator.templates.PushTemplate.Intf

{
  protected static VMTranslator.templates.PushTemplate.ImplData __jamon_setOptionalArguments(VMTranslator.templates.PushTemplate.ImplData p_implData)
  {
    return p_implData;
  }
  public PushTemplateImpl(org.jamon.TemplateManager p_templateManager, VMTranslator.templates.PushTemplate.ImplData p_implData)
  {
    super(p_templateManager, __jamon_setOptionalArguments(p_implData));
  }
  
  public void renderNoFlush(@SuppressWarnings({"unused","hiding"}) final java.io.Writer jamonWriter)
    throws java.io.IOException
  {
    // 1, 1
    jamonWriter.write("// push: push <segment> <index>");
  }
  
  
}
